# Generated by Django 3.2.13 on 2022-05-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poapmodel',
            name='media_type',
            field=models.IntegerField(choices=[('IMAGE', 0), ('VIDEO', 1)]),
        ),
    ]
